const productsData = [
  {
    "id": "904",
    "name": "مایع دستشویی سبز 10 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 19002,
    "consumerPrice": 0,
    "buyPrice": 1146682,
    "packing": 1,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-green_2.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "905",
    "name": "مایع دستشویی نارنجی 10 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 1914400,
    "consumerPrice": 0,
    "buyPrice": 1146682,
    "packing": 1,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-orange_2.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1004",
    "name": "مایع دست سبز 2 کیلویی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 510500,
    "consumerPrice": 0,
    "buyPrice": 392656,
    "packing": 4,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-green_2.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1005",
    "name": "مایع دست نارنجی 2 کیلویی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 510500,
    "consumerPrice": 0,
    "buyPrice": 392656,
    "packing": 4,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-orange_2.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1006",
    "name": "مایع دست صورتی 2 کیلویی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 510500,
    "consumerPrice": 0,
    "buyPrice": 392656,
    "packing": 4,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washin-pink_2.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1007",
    "name": "مایع دست بنفش 2 کیلویی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 510500,
    "consumerPrice": 0,
    "buyPrice": 392656,
    "packing": 4,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-purple_2.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1008",
    "name": "مایع دست سبز 500 گرمی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 167400,
    "consumerPrice": 0,
    "buyPrice": 128811,
    "packing": 12,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-green_2.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1009",
    "name": "مایع دست نارنجی 500 گرمی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 167400,
    "consumerPrice": 0,
    "buyPrice": 128811,
    "packing": 12,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-orange_2.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1010",
    "name": "مایع دست صورتی 500 گرمی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 167400,
    "consumerPrice": 0,
    "buyPrice": 128811,
    "packing": 12,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washin-pink_2.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1011",
    "name": "مایع دست بنفش 500 گرمی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 167400,
    "consumerPrice": 0,
    "buyPrice": 128811,
    "packing": 12,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-purple_2.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1018",
    "name": "مایع دست کرمی 1 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 150000,
    "consumerPrice": 0,
    "buyPrice": 54226,
    "packing": 12,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "ناموجود",
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1019",
    "name": "مایع دست کرمی 350 گرمی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 61600,
    "consumerPrice": 0,
    "buyPrice": 47415,
    "packing": 12,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "ناموجود",
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1021",
    "name": "مایع ظرف 750 گرمی زرد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 96600,
    "consumerPrice": 11,
    "buyPrice": 72796,
    "packing": 12,
    "stock": 11,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-yellow-2700-gr_1.png",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "1022",
    "name": "مایع ظرف 750 گرمی سبز",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 96600,
    "consumerPrice": 11,
    "buyPrice": 72796,
    "packing": 12,
    "stock": 11,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "1026",
    "name": "مایع ظرف 2700 گرمی زرد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 439600,
    "consumerPrice": 4,
    "buyPrice": 338181,
    "packing": 4,
    "stock": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-yellow-2700-gr_1.png",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "1027",
    "name": "مایع ظرف 2700 گرمی سبز",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 439600,
    "consumerPrice": 5,
    "buyPrice": 338181,
    "packing": 4,
    "stock": 25,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "1030",
    "name": "شیشه شوی 800 آبی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 150000,
    "consumerPrice": 10,
    "buyPrice": 115439,
    "packing": 12,
    "stock": 10,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-blue-800_1.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1031",
    "name": "شیشه شوی 800 صورتی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 150000,
    "consumerPrice": 10,
    "buyPrice": 115439,
    "packing": 12,
    "stock": 10,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washin-pink_2.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1032",
    "name": "شیشه شوی 500 آبی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 75700,
    "consumerPrice": 12,
    "buyPrice": 57013,
    "packing": 12,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-blue-800_1.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1033",
    "name": "شیشه شوی 500 صورتی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 75700,
    "consumerPrice": 10,
    "buyPrice": 57013,
    "packing": 12,
    "stock": 10,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washin-pink_2.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1034",
    "name": "شیشه شوی ضد بخار 500",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 88700,
    "consumerPrice": 12,
    "buyPrice": 66835,
    "packing": 12,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/t/steam_1.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1035",
    "name": "شیشه شوی ضد بخار 800",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 120700,
    "consumerPrice": 10,
    "buyPrice": 90932,
    "packing": 12,
    "stock": 10,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/t/steam_1.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1041",
    "name": "اسیدی سرویس بهداشتی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 87200,
    "consumerPrice": 14,
    "buyPrice": 65707,
    "packing": 12,
    "stock": 38,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/4/24.jpg",
    "badge": null,
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "1046",
    "name": "پاک کننده سطوح چوبی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 112100,
    "consumerPrice": 8,
    "buyPrice": 84434,
    "packing": 12,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/4/14_1.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1048",
    "name": "سرویس بهداشتی سرکج زرد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 125100,
    "consumerPrice": 10,
    "buyPrice": 96242,
    "packing": 12,
    "stock": 34,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-yellow-2700-gr_1.png",
    "badge": null,
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "1049",
    "name": "ژل سرکج ویسکوز سرویس بهداشتی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 145600,
    "consumerPrice": 0,
    "buyPrice": 112019,
    "packing": 9,
    "stock": 27,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/4/24.jpg",
    "badge": null,
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "1050",
    "name": "اسپری شیرآلات و سینک ظرفشویی 500",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 87800,
    "consumerPrice": 8,
    "buyPrice": 66120,
    "packing": 12,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460205754_2.jpg",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "1051",
    "name": "اسپری شیرآلات و سینک ظرفشویی 800",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 97000,
    "consumerPrice": 0,
    "buyPrice": 48785,
    "packing": 12,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460205754_2.jpg",
    "badge": "ناموجود",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "1057",
    "name": "فوم لکه بر مبل و فرش",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "home",
    "categoryName": "شستشوی خانه و فرش",
    "price": 104600,
    "consumerPrice": 11,
    "buyPrice": 78826,
    "packing": 12,
    "stock": 11,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/r/a/rafooneh-products-2_1_1.jpg",
    "badge": null,
    "description": "شامپو فرش و موکت رافونه تمیزکننده عمقی الیاف فرش و مبلمان، احیاکننده رنگ و بدون آسیب به بافت فرش."
  },
  {
    "id": "1058",
    "name": "کف لکه بر مخصوص لباس و سرآستین",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "laundry",
    "categoryName": "شوینده لباس",
    "price": 171800,
    "consumerPrice": 5,
    "buyPrice": 132222,
    "packing": 12,
    "stock": 17,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/6/26.jpg",
    "badge": null,
    "description": "شوینده لباس رافونه محافظ بافت و رنگ پارچه، مانع از بور شدن و کدری لباس‌ها با رایحه ماندگار و قدرت لکه‌بری عالی."
  },
  {
    "id": "1059",
    "name": "چندمنظوره آنتی باکتریال",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 56300,
    "consumerPrice": 0,
    "buyPrice": 43338,
    "packing": 12,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460205563-1_1_1.jpg",
    "badge": "ناموجود",
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "1060",
    "name": "اسپری همه کاره 500",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 88600,
    "consumerPrice": 15,
    "buyPrice": 66719,
    "packing": 12,
    "stock": 15,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-pink-800_1.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1061",
    "name": "اسپری همه کاره 800",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 198100,
    "consumerPrice": 8,
    "buyPrice": 152386,
    "packing": 12,
    "stock": 32,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-pink-800_1.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1064",
    "name": "سفیدکننده 1 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 37800,
    "consumerPrice": 7,
    "buyPrice": 28465,
    "packing": 12,
    "stock": 7,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": null,
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "1065",
    "name": "سفیدکننده 2 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 69500,
    "consumerPrice": 5,
    "buyPrice": 52378,
    "packing": 6,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "1066",
    "name": "سفیدکننده 4 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 165900,
    "consumerPrice": 9,
    "buyPrice": 127672,
    "packing": 4,
    "stock": 9,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": null,
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "1068",
    "name": "پاک کننده سنگ و سرامیک 1000 گرمی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 120000,
    "consumerPrice": 0,
    "buyPrice": 103970,
    "packing": 12,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/3/23_1.jpg",
    "badge": "ناموجود",
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1070",
    "name": "اسپری گاز 500",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 83600,
    "consumerPrice": 3,
    "buyPrice": 63010,
    "packing": 12,
    "stock": 3,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/0/10_1.jpg",
    "badge": "تعداد محدود (3 عدد)",
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1071",
    "name": "اسپری گاز 800",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 180400,
    "consumerPrice": 12,
    "buyPrice": 135931,
    "packing": 12,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/0/10_1.jpg",
    "badge": null,
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1072",
    "name": "اسپری گاز شیشه ای",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 137400,
    "consumerPrice": 4,
    "buyPrice": 103523,
    "packing": 12,
    "stock": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/0/10_1.jpg",
    "badge": "تعداد محدود (4 عدد)",
    "description": "پاک‌کننده و اسپری چندمنظوره رافونه تمیزکننده سریع و آسان سطوح، چربی‌زدای قوی بدون برجا گذاشتن لکه و رد آب."
  },
  {
    "id": "1079",
    "name": "لوله بازکن دوقلو 1500 گرمی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 207700,
    "consumerPrice": 11,
    "buyPrice": 156478,
    "packing": 9,
    "stock": 11,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/p/i/pipes.png",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "1080",
    "name": "مشکین شوی 1 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "laundry",
    "categoryName": "شوینده لباس",
    "price": 161400,
    "consumerPrice": 0,
    "buyPrice": 124156,
    "packing": 6,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/b/l/black-wash-1-liter.jpg",
    "badge": null,
    "description": "شوینده لباس رافونه محافظ بافت و رنگ پارچه، مانع از بور شدن و کدری لباس‌ها با رایحه ماندگار و قدرت لکه‌بری عالی."
  },
  {
    "id": "1082",
    "name": "مایع لباسشویی ماشینی و دستی 3 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 690200,
    "consumerPrice": 0,
    "buyPrice": 530935,
    "packing": 4,
    "stock": 100,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/3/_/3_1_1_1.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1084",
    "name": "مایع لباسشویی 2 لیتری",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "laundry",
    "categoryName": "شوینده لباس",
    "price": 135900,
    "consumerPrice": 0,
    "buyPrice": 104569,
    "packing": 6,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/3/_/3_1_1_1.jpg",
    "badge": "ناموجود",
    "description": "شوینده لباس رافونه محافظ بافت و رنگ پارچه، مانع از بور شدن و کدری لباس‌ها با رایحه ماندگار و قدرت لکه‌بری عالی."
  },
  {
    "id": "1085",
    "name": "مایع لباسشویی 2 لیتری آنزیم دار",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "laundry",
    "categoryName": "شوینده لباس",
    "price": 253900,
    "consumerPrice": 0,
    "buyPrice": 270573,
    "packing": 6,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-laundry-2-liters_1_1.png",
    "badge": "ناموجود",
    "description": "شوینده لباس رافونه محافظ بافت و رنگ پارچه، مانع از بور شدن و کدری لباس‌ها با رایحه ماندگار و قدرت لکه‌بری عالی."
  },
  {
    "id": "1111",
    "name": "کیسه فریزر 100 عددی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 45500,
    "consumerPrice": 27,
    "buyPrice": 34266,
    "packing": 50,
    "stock": 27,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460201039-1.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1112",
    "name": "کیسه فریزر تقویمی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 70200,
    "consumerPrice": 0,
    "buyPrice": 58742,
    "packing": 40,
    "stock": 40,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460205259-1.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1113",
    "name": "کیسه فریزر جعبه ای 120 عددی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 48000,
    "consumerPrice": 0,
    "buyPrice": 32384,
    "packing": 36,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460201039-1.jpg",
    "badge": "ناموجود",
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1114",
    "name": "کیسه فریزر رولی 120 عددی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 90000,
    "consumerPrice": 0,
    "buyPrice": 67780,
    "packing": 40,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460201039-1.jpg",
    "badge": "ناموجود",
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1115",
    "name": "کیسه فریزر رولی ضخیم 250 عددی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 149000,
    "consumerPrice": 5,
    "buyPrice": 112213,
    "packing": 15,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204214-1.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1117",
    "name": "زیپ 18*20 تعداد 40 عدد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 137000,
    "consumerPrice": 22,
    "buyPrice": 103176,
    "packing": 24,
    "stock": 22,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/d/o/double-lock-bag-30_2_1.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "1118",
    "name": "زیپ 20*25 تعداد 30 عدد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 137000,
    "consumerPrice": 7,
    "buyPrice": 103176,
    "packing": 24,
    "stock": 7,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/d/o/double-lock-bag-30_2_1.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "1119",
    "name": "زیپ 25*35 تعداد 15 عدد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 137000,
    "consumerPrice": 11,
    "buyPrice": 103176,
    "packing": 24,
    "stock": 11,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/d/o/double-lock-bag-30_2_1.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "1120",
    "name": "فویل آلومینیومی 30 سانتی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 220000,
    "consumerPrice": 13,
    "buyPrice": 165684,
    "packing": 24,
    "stock": 13,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/f/o/foil.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1122",
    "name": "محافظ غذای 40 سانتی 25 متر",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 120000,
    "consumerPrice": 14,
    "buyPrice": 90373,
    "packing": 25,
    "stock": 14,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460203859-1.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1123",
    "name": "محافظ غذای 40 سانتی 20 متر",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 110000,
    "consumerPrice": 10,
    "buyPrice": 82842,
    "packing": 24,
    "stock": 10,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460203859-1.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1124",
    "name": "سفره 50 متری طرح دار",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 195000,
    "consumerPrice": 9,
    "buyPrice": 146856,
    "packing": 24,
    "stock": 9,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460203514-1.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1127",
    "name": "سفره 50 متری ساده",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 175000,
    "consumerPrice": 8,
    "buyPrice": 131794,
    "packing": 24,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204849-1.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1128",
    "name": "سفره یکبار مصرف مجلسی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 169000,
    "consumerPrice": 9,
    "buyPrice": 127275,
    "packing": 12,
    "stock": 9,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204580-1.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1131",
    "name": "کیسه زباله ضخیم یک کیلویی (130*90) 20 عدد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 330000,
    "consumerPrice": 5,
    "buyPrice": 248526,
    "packing": 6,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204740-1.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1132",
    "name": "دستکش یکبار مصرف",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 99000,
    "consumerPrice": 23,
    "buyPrice": 74558,
    "packing": 36,
    "stock": 23,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460202906-1.jpg",
    "badge": null,
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "1133",
    "name": "کیسه زباله سه رول متوسط سبز 42 عدد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 240000,
    "consumerPrice": 14,
    "buyPrice": 180746,
    "packing": 20,
    "stock": 14,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204696-1.jpg",
    "badge": null,
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1134",
    "name": "کیسه زباله سه رول بزرگ آبی 30 عدد",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 190000,
    "consumerPrice": 0,
    "buyPrice": 143091,
    "packing": 20,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204672-1.jpg",
    "badge": "ناموجود",
    "description": "محصولات مصرفی و سلولزی رافونه تهیه شده از مواد اولیه مرغوب و بهداشتی، مقاوم و با دوام بالا برای مصارف روزمره خانه."
  },
  {
    "id": "1254",
    "name": "اسکاچ آفتابگردان",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 30000,
    "consumerPrice": 54,
    "buyPrice": 22640,
    "packing": 26,
    "stock": 54,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/626239650098-1.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "1255",
    "name": "اسکاچ یک زر شیرینگ آبی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 25000,
    "consumerPrice": 57,
    "buyPrice": 9037,
    "packing": 39,
    "stock": 57,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-blue-800_1.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "1256",
    "name": "اسکاچ دو زر شیرینگ قرمز",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 25000,
    "consumerPrice": 0,
    "buyPrice": 9790,
    "packing": 39,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/626239650098-1.jpg",
    "badge": "ناموجود",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "1257",
    "name": "اسکاچ طرح دار شیرینگ سبز",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 25000,
    "consumerPrice": 8,
    "buyPrice": 20805,
    "packing": 39,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-green_2.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "1263",
    "name": "سیم ظرفشویی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 30000,
    "consumerPrice": 13,
    "buyPrice": 24354,
    "packing": 36,
    "stock": 13,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6262396500050-1.jpg",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "1280",
    "name": "دستمال چند منظوره آشپزخانه",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 52200,
    "consumerPrice": 0,
    "buyPrice": 49140,
    "packing": 12,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6262396500111-1.jpg",
    "badge": "ناموجود",
    "description": "مایع دستشویی رافونه با فرمولاسیون نرم‌کننده و مرطوب‌کننده پوست دست، دارای رایحه مطبوع و سازگار با انواع پوست بدون ایجاد خشکی و حساسیت."
  },
  {
    "id": "2161",
    "name": "شامپو head & shoulders MENTHOL FRESH",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 500000,
    "consumerPrice": 0,
    "buyPrice": 425000,
    "packing": 1,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "ناموجود",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2162",
    "name": "شامپو head & shoulders CLASSIC CLEAN",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 500000,
    "consumerPrice": 0,
    "buyPrice": 425000,
    "packing": 1,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "ناموجود",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2163",
    "name": "شامپو head & shoulders DRY SCALP",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 500000,
    "consumerPrice": 1,
    "buyPrice": 425000,
    "packing": 1,
    "stock": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "تعداد محدود (1 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2164",
    "name": "شامپو head & shoulders SMOOTH & SILKY",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 500000,
    "consumerPrice": 3,
    "buyPrice": 425000,
    "packing": 1,
    "stock": 3,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "تعداد محدود (3 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2201",
    "name": "قرص ماشین ظرفشوییfairy 60",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1900000,
    "consumerPrice": 2,
    "buyPrice": 1615000,
    "packing": 1,
    "stock": 2,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (2 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2202",
    "name": "قرص ماشین ظرفشوییfairy 70",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 2200000,
    "consumerPrice": 1,
    "buyPrice": 1870000,
    "packing": 1,
    "stock": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (1 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2203",
    "name": "قرص ماشین ظرفشوییfairy 100",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 3100000,
    "consumerPrice": 7,
    "buyPrice": 2635000,
    "packing": 1,
    "stock": 7,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2206",
    "name": "قرص ماشین ظرفشوییfairy 90",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 460000,
    "consumerPrice": 0,
    "buyPrice": 391000,
    "packing": 1,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "ناموجود",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2207",
    "name": "قرص ماشین ظرفشویی fairy platinum 96",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 3200000,
    "consumerPrice": 0,
    "buyPrice": 2720000,
    "packing": 1,
    "stock": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (1 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2208",
    "name": "قرص ماشین ظرفشویی fairy platinum 72",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 2700000,
    "consumerPrice": 0,
    "buyPrice": 2295000,
    "packing": 1,
    "stock": 2,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (2 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2211",
    "name": "قرص ماشین ظرفشوییfinish quantum 72",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1800000,
    "consumerPrice": 1,
    "buyPrice": 1530000,
    "packing": 1,
    "stock": 3,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (3 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2213",
    "name": "قرص ظرفشوییfinish Ultimate 60",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1600000,
    "consumerPrice": 0,
    "buyPrice": 1360000,
    "packing": 1,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "ناموجود",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2214",
    "name": "قرص ظرفشوییfinish Ultimate 65",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1800000,
    "consumerPrice": 1,
    "buyPrice": 1530000,
    "packing": 1,
    "stock": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (1 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2215",
    "name": "قرص ظرفشوییfinish Ultimate 85",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 2300000,
    "consumerPrice": 1,
    "buyPrice": 1955000,
    "packing": 1,
    "stock": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (1 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2216",
    "name": "ژل ماشین ظرفشویی finish",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1400000,
    "consumerPrice": 3,
    "buyPrice": 1190000,
    "packing": 1,
    "stock": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (4 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2217",
    "name": "جرم گیر ماشین ظرفشویی BOSCH",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 100000,
    "consumerPrice": 0,
    "buyPrice": 85000,
    "packing": 1,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "ناموجود",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2218",
    "name": "جرم گیر فینیش",
    "brand": "foreign",
    "brandName": "محصولات خارجی",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 600000,
    "consumerPrice": 0,
    "buyPrice": 510000,
    "packing": 1,
    "stock": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/1/11_1_.jpg",
    "badge": "تعداد محدود (1 عدد)",
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "2221",
    "name": "بوگیر ماشین ظرفشویی Prill",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 400000,
    "consumerPrice": 0,
    "buyPrice": 340000,
    "packing": 1,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "ناموجود",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2222",
    "name": "بوگیر ماشین ظرفشویی finish",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 500000,
    "consumerPrice": 2,
    "buyPrice": 425000,
    "packing": 1,
    "stock": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تعداد محدود (4 عدد)",
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2231",
    "name": "جلادهنده 800 ظرفشویی finish اصل ترک",
    "brand": "foreign",
    "brandName": "محصولات خارجی",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1000000,
    "consumerPrice": 2,
    "buyPrice": 850000,
    "packing": 1,
    "stock": 6,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2232",
    "name": "نمک ماشین ظرفشویی finish اصل ترک",
    "brand": "foreign",
    "brandName": "محصولات خارجی",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 600000,
    "consumerPrice": 8,
    "buyPrice": 510000,
    "packing": 1,
    "stock": 8,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": null,
    "description": "مایع ظرفشویی رافونه غلیظ و با قدرت چربی‌زدایی فوق‌العاده بالا، درخشان‌کننده ظروف، دارای گلیسیرین جهت محافظت از پوست دست."
  },
  {
    "id": "2301",
    "name": "خمیر دندان colgate triple",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 300000,
    "consumerPrice": 4,
    "buyPrice": 255000,
    "packing": 1,
    "stock": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تعداد محدود (4 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2302",
    "name": "خمیر دندان colgate family",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 170000,
    "consumerPrice": 0,
    "buyPrice": 144500,
    "packing": 1,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "ناموجود",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2303",
    "name": "خمیر دندان Colgate سفیدکننده دوقلو",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 350000,
    "consumerPrice": 5,
    "buyPrice": 297500,
    "packing": 1,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "2354",
    "name": "مسواک Oral-B سه عددی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 550000,
    "consumerPrice": 9,
    "buyPrice": 467500,
    "packing": 1,
    "stock": 9,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460202906-1.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2355",
    "name": "مسواک سیگنال",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 220000,
    "consumerPrice": 11,
    "buyPrice": 187000,
    "packing": 1,
    "stock": 11,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2359",
    "name": "مسواک کلگیت مکس فرش",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "home",
    "categoryName": "شستشوی خانه و فرش",
    "price": 250000,
    "consumerPrice": 12,
    "buyPrice": 212500,
    "packing": 1,
    "stock": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": null,
    "description": "شامپو فرش و موکت رافونه تمیزکننده عمقی الیاف فرش و مبلمان، احیاکننده رنگ و بدون آسیب به بافت فرش."
  },
  {
    "id": "2360",
    "name": "مسواک پرکینز",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 150000,
    "consumerPrice": 24,
    "buyPrice": 127500,
    "packing": 1,
    "stock": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2362",
    "name": "مسواک بچگانه 5 تا 7 سال HiDent",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 50000,
    "consumerPrice": 1,
    "buyPrice": 42500,
    "packing": 1,
    "stock": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تعداد محدود (1 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2363",
    "name": "مسواک بچگانه 7 تا 10 سال HiDent",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 50000,
    "consumerPrice": 9,
    "buyPrice": 42500,
    "packing": 1,
    "stock": 9,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": null,
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2411",
    "name": "صابون لوکس گل رز",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 4,
    "buyPrice": 170000,
    "packing": 1,
    "stock": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تعداد محدود (4 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2412",
    "name": "صابون لوکس یاسمین",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 5,
    "buyPrice": 170000,
    "packing": 1,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2413",
    "name": "صابون لوکس رمانتیک",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 3,
    "buyPrice": 170000,
    "packing": 1,
    "stock": 3,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تعداد محدود (3 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2414",
    "name": "صابون لوکس گاردنیا",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 5,
    "buyPrice": 170000,
    "packing": 1,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2415",
    "name": "صابون لوکس زنبق",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 3,
    "buyPrice": 170000,
    "packing": 1,
    "stock": 3,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تعداد محدود (3 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2416",
    "name": "صابون لوکس رز سفید",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 200000,
    "consumerPrice": 5,
    "buyPrice": 170000,
    "packing": 1,
    "stock": 5,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "تعداد محدود (5 عدد)",
    "description": "جرم‌گیر و ضدعفونی‌کننده رافونه از بین برنده ۹۹.۹٪ باکتری‌ها و جرم‌های سرسخت، درخشان‌کننده سرویس بهداشتی و کاشی."
  },
  {
    "id": "2611",
    "name": "مام NIVEA Black & White",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 300000,
    "consumerPrice": 0,
    "buyPrice": 255000,
    "packing": 1,
    "stock": 0,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "ناموجود",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  },
  {
    "id": "2621",
    "name": "نخ دندان اورال بی",
    "brand": "rafooneh",
    "brandName": "برند رافونه",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 450000,
    "consumerPrice": 2,
    "buyPrice": 382500,
    "packing": 1,
    "stock": 2,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تعداد محدود (2 عدد)",
    "description": "محصول باکیفیت و استاندارد رافونه تولید شده با بهترین مواد اولیه و فرمولاسیون تخصصی."
  }
];
