const productsData = [
  {
    "id": "904",
    "name": "مایع دستشویی سبز 10 لیتری",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 1000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-green_2.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مایع دستشویی سبز 10 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "905",
    "name": "مایع دستشویی نارنجی 10 لیتری",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 1914400,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-orange_2.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مایع دستشویی نارنجی 10 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1004",
    "name": "مایع دست سبز 2 کیلویی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 510500,
    "consumerPrice": 0,
    "packing": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-green_2.jpg",
    "badge": "کارتن 4 تایی",
    "description": "محصول اصلی رافونه - مایع دست سبز 2 کیلویی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1005",
    "name": "مایع دست نارنجی 2 کیلویی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 510500,
    "consumerPrice": 0,
    "packing": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-orange_2.jpg",
    "badge": "کارتن 4 تایی",
    "description": "محصول اصلی رافونه - مایع دست نارنجی 2 کیلویی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1006",
    "name": "مایع دست صورتی 2 کیلویی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 510500,
    "consumerPrice": 0,
    "packing": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washin-pink_2.jpg",
    "badge": "کارتن 4 تایی",
    "description": "محصول اصلی رافونه - مایع دست صورتی 2 کیلویی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1007",
    "name": "مایع دست بنفش 2 کیلویی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 510500,
    "consumerPrice": 0,
    "packing": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-purple_2.jpg",
    "badge": "کارتن 4 تایی",
    "description": "محصول اصلی رافونه - مایع دست بنفش 2 کیلویی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1008",
    "name": "مایع دست سبز 500 گرمی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 167400,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-green_2.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - مایع دست سبز 500 گرمی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1009",
    "name": "مایع دست نارنجی 500 گرمی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 167400,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-orange_2.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - مایع دست نارنجی 500 گرمی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1010",
    "name": "مایع دست صورتی 500 گرمی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 167400,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washin-pink_2.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - مایع دست صورتی 500 گرمی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1011",
    "name": "مایع دست بنفش 500 گرمی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 167400,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-purple_2.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - مایع دست بنفش 500 گرمی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1018",
    "name": "مایع دست کرمی 1 لیتری",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 150000,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - مایع دست کرمی 1 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1019",
    "name": "مایع دست کرمی 350 گرمی",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 61600,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - مایع دست کرمی 350 گرمی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1021",
    "name": "مایع ظرف 750 گرمی زرد",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 96600,
    "consumerPrice": 11,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-yellow-2700-gr_1.png",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - مایع ظرف 750 گرمی زرد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1022",
    "name": "مایع ظرف 750 گرمی سبز",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 96600,
    "consumerPrice": 11,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - مایع ظرف 750 گرمی سبز. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1026",
    "name": "مایع ظرف 2700 گرمی زرد",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 439600,
    "consumerPrice": 4,
    "packing": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-yellow-2700-gr_1.png",
    "badge": "کارتن 4 تایی",
    "description": "محصول اصلی رافونه - مایع ظرف 2700 گرمی زرد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1027",
    "name": "مایع ظرف 2700 گرمی سبز",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 439600,
    "consumerPrice": 5,
    "packing": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "کارتن 4 تایی",
    "description": "محصول اصلی رافونه - مایع ظرف 2700 گرمی سبز. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1030",
    "name": "شیشه شوی 800 آبی",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 150000,
    "consumerPrice": 10,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-blue-800_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - شیشه شوی 800 آبی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1031",
    "name": "شیشه شوی 800 صورتی",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 150000,
    "consumerPrice": 10,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washin-pink_2.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - شیشه شوی 800 صورتی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1032",
    "name": "شیشه شوی 500 آبی",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 75700,
    "consumerPrice": 12,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-blue-800_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - شیشه شوی 500 آبی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1033",
    "name": "شیشه شوی 500 صورتی",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 75700,
    "consumerPrice": 10,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washin-pink_2.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - شیشه شوی 500 صورتی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1034",
    "name": "شیشه شوی ضد بخار 500",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 88700,
    "consumerPrice": 12,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/t/steam_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - شیشه شوی ضد بخار 500. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1035",
    "name": "شیشه شوی ضد بخار 800",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 120700,
    "consumerPrice": 10,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/t/steam_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - شیشه شوی ضد بخار 800. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1041",
    "name": "اسیدی سرویس بهداشتی",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 87200,
    "consumerPrice": 14,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/4/24.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - اسیدی سرویس بهداشتی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1046",
    "name": "پاک کننده سطوح چوبی",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 112100,
    "consumerPrice": 8,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/4/14_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - پاک کننده سطوح چوبی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1048",
    "name": "سرویس بهداشتی سرکج زرد",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 125100,
    "consumerPrice": 10,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-yellow-2700-gr_1.png",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - سرویس بهداشتی سرکج زرد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1049",
    "name": "ژل سرکج ویسکوز سرویس بهداشتی",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 145600,
    "consumerPrice": 0,
    "packing": 9,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/4/24.jpg",
    "badge": "کارتن 9 تایی",
    "description": "محصول اصلی رافونه - ژل سرکج ویسکوز سرویس بهداشتی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1050",
    "name": "اسپری شیرآلات و سینک ظرفشویی 500",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 87800,
    "consumerPrice": 8,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460205754_2.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - اسپری شیرآلات و سینک ظرفشویی 500. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1051",
    "name": "اسپری شیرآلات و سینک ظرفشویی 800",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 97000,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460205754_2.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - اسپری شیرآلات و سینک ظرفشویی 800. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1057",
    "name": "فوم لکه بر مبل و فرش",
    "category": "home",
    "categoryName": "شستشوی خانه و فرش",
    "price": 104600,
    "consumerPrice": 11,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/r/a/rafooneh-products-2_1_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - فوم لکه بر مبل و فرش. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1058",
    "name": "کف لکه بر مخصوص لباس و سرآستین",
    "category": "laundry",
    "categoryName": "شوینده لباس",
    "price": 171800,
    "consumerPrice": 5,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/6/26.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - کف لکه بر مخصوص لباس و سرآستین. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1059",
    "name": "چندمنظوره آنتی باکتریال",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 56300,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460205563-1_1_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - چندمنظوره آنتی باکتریال. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1060",
    "name": "اسپری همه کاره 500",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 88600,
    "consumerPrice": 15,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-pink-800_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - اسپری همه کاره 500. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1061",
    "name": "اسپری همه کاره 800",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 198100,
    "consumerPrice": 8,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-pink-800_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - اسپری همه کاره 800. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1064",
    "name": "سفیدکننده 1 لیتری",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 37800,
    "consumerPrice": 7,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - سفیدکننده 1 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1065",
    "name": "سفیدکننده 2 لیتری",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 69500,
    "consumerPrice": 5,
    "packing": 6,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "کارتن 6 تایی",
    "description": "محصول اصلی رافونه - سفیدکننده 2 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1066",
    "name": "سفیدکننده 4 لیتری",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 165900,
    "consumerPrice": 9,
    "packing": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "کارتن 4 تایی",
    "description": "محصول اصلی رافونه - سفیدکننده 4 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1068",
    "name": "پاک کننده سنگ و سرامیک 1000 گرمی",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 120000,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/3/23_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - پاک کننده سنگ و سرامیک 1000 گرمی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1070",
    "name": "اسپری گاز 500",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 83600,
    "consumerPrice": 3,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/0/10_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - اسپری گاز 500. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1071",
    "name": "اسپری گاز 800",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 180400,
    "consumerPrice": 12,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/0/10_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - اسپری گاز 800. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1072",
    "name": "اسپری گاز شیشه ای",
    "category": "cleaners",
    "categoryName": "پاک‌کننده و اسپری",
    "price": 137400,
    "consumerPrice": 4,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/0/10_1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - اسپری گاز شیشه ای. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1079",
    "name": "لوله بازکن دوقلو 1500 گرمی",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 207700,
    "consumerPrice": 11,
    "packing": 9,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/p/i/pipes.png",
    "badge": "کارتن 9 تایی",
    "description": "محصول اصلی رافونه - لوله بازکن دوقلو 1500 گرمی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1080",
    "name": "مشکین شوی 1 لیتری",
    "category": "laundry",
    "categoryName": "شوینده لباس",
    "price": 161400,
    "consumerPrice": 0,
    "packing": 6,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/b/l/black-wash-1-liter.jpg",
    "badge": "کارتن 6 تایی",
    "description": "محصول اصلی رافونه - مشکین شوی 1 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1082",
    "name": "مایع لباسشویی ماشینی و دستی 3 لیتری",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 690200,
    "consumerPrice": 0,
    "packing": 4,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/3/_/3_1_1_1.jpg",
    "badge": "کارتن 4 تایی",
    "description": "محصول اصلی رافونه - مایع لباسشویی ماشینی و دستی 3 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1084",
    "name": "مایع لباسشویی 2 لیتری",
    "category": "laundry",
    "categoryName": "شوینده لباس",
    "price": 135900,
    "consumerPrice": 0,
    "packing": 6,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/3/_/3_1_1_1.jpg",
    "badge": "کارتن 6 تایی",
    "description": "محصول اصلی رافونه - مایع لباسشویی 2 لیتری. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1085",
    "name": "مایع لباسشویی 2 لیتری آنزیم دار",
    "category": "laundry",
    "categoryName": "شوینده لباس",
    "price": 253900,
    "consumerPrice": 0,
    "packing": 6,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-laundry-2-liters_1_1.png",
    "badge": "کارتن 6 تایی",
    "description": "محصول اصلی رافونه - مایع لباسشویی 2 لیتری آنزیم دار. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1111",
    "name": "کیسه فریزر 100 عددی",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 45500,
    "consumerPrice": 27,
    "packing": 50,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460201039-1.jpg",
    "badge": "کارتن 50 تایی",
    "description": "محصول اصلی رافونه - کیسه فریزر 100 عددی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1112",
    "name": "کیسه فریزر تقویمی",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 70200,
    "consumerPrice": 0,
    "packing": 40,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460205259-1.jpg",
    "badge": "کارتن 40 تایی",
    "description": "محصول اصلی رافونه - کیسه فریزر تقویمی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1113",
    "name": "کیسه فریزر جعبه ای 120 عددی",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 48000,
    "consumerPrice": 0,
    "packing": 36,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460201039-1.jpg",
    "badge": "کارتن 36 تایی",
    "description": "محصول اصلی رافونه - کیسه فریزر جعبه ای 120 عددی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1114",
    "name": "کیسه فریزر رولی 120 عددی",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 90000,
    "consumerPrice": 0,
    "packing": 40,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460201039-1.jpg",
    "badge": "کارتن 40 تایی",
    "description": "محصول اصلی رافونه - کیسه فریزر رولی 120 عددی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1115",
    "name": "کیسه فریزر رولی ضخیم 250 عددی",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 149000,
    "consumerPrice": 5,
    "packing": 15,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204214-1.jpg",
    "badge": "کارتن 15 تایی",
    "description": "محصول اصلی رافونه - کیسه فریزر رولی ضخیم 250 عددی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1117",
    "name": "زیپ 18*20 تعداد 40 عدد",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 137000,
    "consumerPrice": 22,
    "packing": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/d/o/double-lock-bag-30_2_1.jpg",
    "badge": "کارتن 24 تایی",
    "description": "محصول اصلی رافونه - زیپ 18*20 تعداد 40 عدد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1118",
    "name": "زیپ 20*25 تعداد 30 عدد",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 137000,
    "consumerPrice": 7,
    "packing": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/d/o/double-lock-bag-30_2_1.jpg",
    "badge": "کارتن 24 تایی",
    "description": "محصول اصلی رافونه - زیپ 20*25 تعداد 30 عدد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1119",
    "name": "زیپ 25*35 تعداد 15 عدد",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 137000,
    "consumerPrice": 11,
    "packing": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/d/o/double-lock-bag-30_2_1.jpg",
    "badge": "کارتن 24 تایی",
    "description": "محصول اصلی رافونه - زیپ 25*35 تعداد 15 عدد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1120",
    "name": "فویل آلومینیومی 30 سانتی",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 220000,
    "consumerPrice": 13,
    "packing": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/f/o/foil.jpg",
    "badge": "کارتن 24 تایی",
    "description": "محصول اصلی رافونه - فویل آلومینیومی 30 سانتی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1122",
    "name": "محافظ غذای 40 سانتی 25 متر",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 120000,
    "consumerPrice": 14,
    "packing": 25,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460203859-1.jpg",
    "badge": "کارتن 25 تایی",
    "description": "محصول اصلی رافونه - محافظ غذای 40 سانتی 25 متر. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1123",
    "name": "محافظ غذای 40 سانتی 20 متر",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 110000,
    "consumerPrice": 10,
    "packing": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460203859-1.jpg",
    "badge": "کارتن 24 تایی",
    "description": "محصول اصلی رافونه - محافظ غذای 40 سانتی 20 متر. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1124",
    "name": "سفره 50 متری طرح دار",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 195000,
    "consumerPrice": 9,
    "packing": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460203514-1.jpg",
    "badge": "کارتن 24 تایی",
    "description": "محصول اصلی رافونه - سفره 50 متری طرح دار. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1127",
    "name": "سفره 50 متری ساده",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 175000,
    "consumerPrice": 8,
    "packing": 24,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204849-1.jpg",
    "badge": "کارتن 24 تایی",
    "description": "محصول اصلی رافونه - سفره 50 متری ساده. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1128",
    "name": "سفره یکبار مصرف مجلسی",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 169000,
    "consumerPrice": 9,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204580-1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - سفره یکبار مصرف مجلسی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1131",
    "name": "کیسه زباله ضخیم یک کیلویی (130*90) 20 عدد",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 330000,
    "consumerPrice": 5,
    "packing": 6,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204740-1.jpg",
    "badge": "کارتن 6 تایی",
    "description": "محصول اصلی رافونه - کیسه زباله ضخیم یک کیلویی (130*90) 20 عدد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1132",
    "name": "دستکش یکبار مصرف",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 99000,
    "consumerPrice": 23,
    "packing": 36,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460202906-1.jpg",
    "badge": "کارتن 36 تایی",
    "description": "محصول اصلی رافونه - دستکش یکبار مصرف. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1133",
    "name": "کیسه زباله سه رول متوسط سبز 42 عدد",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 240000,
    "consumerPrice": 14,
    "packing": 20,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204696-1.jpg",
    "badge": "کارتن 20 تایی",
    "description": "محصول اصلی رافونه - کیسه زباله سه رول متوسط سبز 42 عدد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1134",
    "name": "کیسه زباله سه رول بزرگ آبی 30 عدد",
    "category": "cellulosic",
    "categoryName": "لوازم مصرفی و سلولزی",
    "price": 190000,
    "consumerPrice": 0,
    "packing": 20,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460204672-1.jpg",
    "badge": "کارتن 20 تایی",
    "description": "محصول اصلی رافونه - کیسه زباله سه رول بزرگ آبی 30 عدد. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1254",
    "name": "اسکاچ آفتابگردان",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 30000,
    "consumerPrice": 54,
    "packing": 26,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/626239650098-1.jpg",
    "badge": "کارتن 26 تایی",
    "description": "محصول اصلی رافونه - اسکاچ آفتابگردان. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1255",
    "name": "اسکاچ یک زر شیرینگ آبی",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 25000,
    "consumerPrice": 57,
    "packing": 39,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/g/l/glass-blue-800_1.jpg",
    "badge": "کارتن 39 تایی",
    "description": "محصول اصلی رافونه - اسکاچ یک زر شیرینگ آبی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1256",
    "name": "اسکاچ دو زر شیرینگ قرمز",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 25000,
    "consumerPrice": 0,
    "packing": 39,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/626239650098-1.jpg",
    "badge": "کارتن 39 تایی",
    "description": "محصول اصلی رافونه - اسکاچ دو زر شیرینگ قرمز. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1257",
    "name": "اسکاچ طرح دار شیرینگ سبز",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 25000,
    "consumerPrice": 8,
    "packing": 39,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/h/a/hand-washing-green_2.jpg",
    "badge": "کارتن 39 تایی",
    "description": "محصول اصلی رافونه - اسکاچ طرح دار شیرینگ سبز. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1263",
    "name": "سیم ظرفشویی",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 30000,
    "consumerPrice": 13,
    "packing": 36,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6262396500050-1.jpg",
    "badge": "کارتن 36 تایی",
    "description": "محصول اصلی رافونه - سیم ظرفشویی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "1280",
    "name": "دستمال چند منظوره آشپزخانه",
    "category": "handwash",
    "categoryName": "مایع دستشویی",
    "price": 52200,
    "consumerPrice": 0,
    "packing": 12,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6262396500111-1.jpg",
    "badge": "کارتن 12 تایی",
    "description": "محصول اصلی رافونه - دستمال چند منظوره آشپزخانه. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2161",
    "name": "شامپو head & shoulders MENTHOL FRESH",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 500000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - شامپو head & shoulders MENTHOL FRESH. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2162",
    "name": "شامپو head & shoulders CLASSIC CLEAN",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 500000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - شامپو head & shoulders CLASSIC CLEAN. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2163",
    "name": "شامپو head & shoulders DRY SCALP",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 500000,
    "consumerPrice": 1,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - شامپو head & shoulders DRY SCALP. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2164",
    "name": "شامپو head & shoulders SMOOTH & SILKY",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 500000,
    "consumerPrice": 3,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - شامپو head & shoulders SMOOTH & SILKY. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2201",
    "name": "قرص ماشین ظرفشوییfairy 60",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1900000,
    "consumerPrice": 2,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ماشین ظرفشوییfairy 60. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2202",
    "name": "قرص ماشین ظرفشوییfairy 70",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 2200000,
    "consumerPrice": 1,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ماشین ظرفشوییfairy 70. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2203",
    "name": "قرص ماشین ظرفشوییfairy 100",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 3100000,
    "consumerPrice": 7,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ماشین ظرفشوییfairy 100. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2206",
    "name": "قرص ماشین ظرفشوییfairy 90",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 460000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ماشین ظرفشوییfairy 90. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2207",
    "name": "قرص ماشین ظرفشویی fairy platinum 96",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 3200000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ماشین ظرفشویی fairy platinum 96. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2208",
    "name": "قرص ماشین ظرفشویی fairy platinum 72",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 2700000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ماشین ظرفشویی fairy platinum 72. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2211",
    "name": "قرص ماشین ظرفشوییfinish quantum 72",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1800000,
    "consumerPrice": 1,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ماشین ظرفشوییfinish quantum 72. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2213",
    "name": "قرص ظرفشوییfinish Ultimate 60",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1600000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ظرفشوییfinish Ultimate 60. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2214",
    "name": "قرص ظرفشوییfinish Ultimate 65",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1800000,
    "consumerPrice": 1,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ظرفشوییfinish Ultimate 65. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2215",
    "name": "قرص ظرفشوییfinish Ultimate 85",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 2300000,
    "consumerPrice": 1,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - قرص ظرفشوییfinish Ultimate 85. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2216",
    "name": "ژل ماشین ظرفشویی finish",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1400000,
    "consumerPrice": 3,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - ژل ماشین ظرفشویی finish. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2217",
    "name": "جرم گیر ماشین ظرفشویی BOSCH",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 100000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - جرم گیر ماشین ظرفشویی BOSCH. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2218",
    "name": "جرم گیر فینیش",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 600000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/1/1/11_1_.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - جرم گیر فینیش. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2221",
    "name": "بوگیر ماشین ظرفشویی Prill",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 400000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - بوگیر ماشین ظرفشویی Prill. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2222",
    "name": "بوگیر ماشین ظرفشویی finish",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 500000,
    "consumerPrice": 2,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - بوگیر ماشین ظرفشویی finish. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2231",
    "name": "جلادهنده 800 ظرفشویی finish اصل ترک",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 1000000,
    "consumerPrice": 2,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - جلادهنده 800 ظرفشویی finish اصل ترک. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2232",
    "name": "نمک ماشین ظرفشویی finish اصل ترک",
    "category": "dishwash",
    "categoryName": "مایع ظرفشویی",
    "price": 600000,
    "consumerPrice": 8,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/l/i/liquid-dishwashing-glycerin-green-2700-gr_1.png",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - نمک ماشین ظرفشویی finish اصل ترک. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2301",
    "name": "خمیر دندان colgate triple",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 300000,
    "consumerPrice": 4,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - خمیر دندان colgate triple. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2302",
    "name": "خمیر دندان colgate family",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 170000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - خمیر دندان colgate family. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2303",
    "name": "خمیر دندان Colgate سفیدکننده دوقلو",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 350000,
    "consumerPrice": 5,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - خمیر دندان Colgate سفیدکننده دوقلو. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2354",
    "name": "مسواک Oral-B سه عددی",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 550000,
    "consumerPrice": 9,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/6/2/6261460202906-1.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مسواک Oral-B سه عددی. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2355",
    "name": "مسواک سیگنال",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 220000,
    "consumerPrice": 11,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مسواک سیگنال. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2359",
    "name": "مسواک کلگیت مکس فرش",
    "category": "home",
    "categoryName": "شستشوی خانه و فرش",
    "price": 250000,
    "consumerPrice": 12,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/2/1/21_1.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مسواک کلگیت مکس فرش. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2360",
    "name": "مسواک پرکینز",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 150000,
    "consumerPrice": 24,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مسواک پرکینز. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2362",
    "name": "مسواک بچگانه 5 تا 7 سال HiDent",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 50000,
    "consumerPrice": 1,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مسواک بچگانه 5 تا 7 سال HiDent. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2363",
    "name": "مسواک بچگانه 7 تا 10 سال HiDent",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 50000,
    "consumerPrice": 9,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مسواک بچگانه 7 تا 10 سال HiDent. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2411",
    "name": "صابون لوکس گل رز",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 4,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - صابون لوکس گل رز. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2412",
    "name": "صابون لوکس یاسمین",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 5,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - صابون لوکس یاسمین. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2413",
    "name": "صابون لوکس رمانتیک",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 3,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - صابون لوکس رمانتیک. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2414",
    "name": "صابون لوکس گاردنیا",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 5,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - صابون لوکس گاردنیا. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2415",
    "name": "صابون لوکس زنبق",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 200000,
    "consumerPrice": 3,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - صابون لوکس زنبق. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2416",
    "name": "صابون لوکس رز سفید",
    "category": "sanitary",
    "categoryName": "جرم‌گیر و ضدعفونی‌کننده",
    "price": 200000,
    "consumerPrice": 5,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/c/r/creamy-hand-wash_1_1.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - صابون لوکس رز سفید. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2611",
    "name": "مام NIVEA Black & White",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 300000,
    "consumerPrice": 0,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - مام NIVEA Black & White. دریافت مستقیم از گوگل شیت."
  },
  {
    "id": "2621",
    "name": "نخ دندان اورال بی",
    "category": "other",
    "categoryName": "سایر شوینده‌ها",
    "price": 450000,
    "consumerPrice": 2,
    "packing": 1,
    "image": "https://rafooneh.com/media/catalog/product/cache/13fb5134717fc87cd9b03caf5e4a36c1/s/a/sanitary-protective-coating-large.jpg",
    "badge": "تحویل مستقیم",
    "description": "محصول اصلی رافونه - نخ دندان اورال بی. دریافت مستقیم از گوگل شیت."
  }
];
